---
# tasks/main.yml per ssh_key_install

- name: Create /postgresql/.ssh directory
  file:
    path: /postgresql/.ssh
    state: directory
    owner: postgres
    group: postgres
    mode: '0700'

- name: Generate SSH keys on master1
  command:
    cmd: ssh-keygen -t rsa -f /postgresql/.ssh/id_rsa -N ""
  when: "'{{ pgpool_primary_node_ip }}' in ansible_host"
  become: yes
  become_user: postgres
  args:
    creates: /postgresql/.ssh/id_rsa

- name: Ensure SSH public key is available
  fetch:
    src: /postgresql/.ssh/id_rsa.pub
    dest: "/tmp/id_rsa.pub"
    flat: yes
  when: "'{{ pgpool_primary_node_ip }}' in ansible_host"
