---

- name: Configure | Upload pgpool.conf
  template:
    src: pgpool.conf.j2
    dest: "/etc/pgpool2/pgpool.conf"
    backup: true
    owner: "postgres"
    mode: 0775

- name: Configure | Upload pool_hba.conf
  template:
    src: pool_hba.conf.j2
    dest: "{{ pgpool_home_directory }}/pool_hba.conf"
    owner: "postgres"
    mode: 0775
  when: 
    - pgpool_enable_pool_hba | bool 
    - pgpool_pool_hba_entries | length > 0

- name: Replace content of /etc/pgpool2/follow_master.sh
  copy:
    dest: "/etc/pgpool2/follow_master.sh"
    src: "{{ playbook_dir }}/files/pgpool/follow_master.sh"
    owner: postgres
    group: postgres
    mode: '0777'

- name: Replace content of /etc/pgpool2/failover.sh
  copy:
    dest: "/etc/pgpool2/failover.sh"
    src: "{{ playbook_dir }}/files/pgpool/failover.sh"
    owner: postgres
    group: postgres
    mode: '0777'

- name: Configure | Generate pool_passwd file using md5 auth method
  shell:
    cmd: |
      pg_md5 --md5auth --username={{ item.username }} {{ item.password }}
  loop: "{{ pgpool_passwd_users_md5 }}"
  when: pgpool_passwd_use_md5 | bool

# starting from "pool_passwd" file 
- name: Configure .pgpass file for postgres user
  shell:
    cmd: |
      sed 's/.*/*:*:*:&/' {{ pgpool_pool_passwd }} | sed 's/*:*:*:repl/replication:repl/' > {{ pgpool_postgresql_home_directory }}/.pgpass
      chmod 600 {{ pgpool_postgresql_home_directory }}/.pgpass
      chown postgres:postgres {{ pgpool_postgresql_home_directory }}/.pgpass

 #- name: Configure | Upload pcp.conf
 # template:
 #   src: pcp.conf.j2
 #   dest: "{{ pgpool_home_directory }}/pcp.conf"
 #   mode: 0775

#- name: Configure | Upload .pcppass file (pgpool)
#  template:
#    src: pcppass.j2
#    dest: "{{ pgpool_postgresql_home_directory }}/.pcppass"
#    mode: 0600

- name: Configure pcp.conf
  shell:
    cmd: |
      echo '{{ item.username }}:'`pg_md5 {{ item.password }}` >> /etc/pgpool2/pcp.conf 
  with_items: "{{ pgpool_passwd_users_md5 }}"

- name: Configure | Upload .pcppass file (pgpool)
  become: true
  become_user: postgres
  shell:
    cmd: |
      echo 'localhost:9898:pgpool:{{ pgpool_password }}' > ~/.pcppass
      echo '{{ pgpool_delegate_IP }}:9898:pgpool:{{ pgpool_password }}' >> ~/.pcppass
      chmod 600 ~/.pcppass

- name: configure pgpool_node_id on each node
  #debug:
  #  msg: "The index of {{ inventory_hostname }} is {{ ansible_play_hosts.index(inventory_hostname) }}"  
  #  var: ansible_host
    #var: ansible_all_ipv4_addresses[0]
  #  msg: "Host: {{ item.0 }} (Index: {{ item.1 }})"
  shell: "echo {{ ansible_play_hosts.index(inventory_hostname) }} > {{ pgpool_home_directory }}/pgpool_node_id"
  #with_indexed_items: "{{ ansible_play_hosts_all }}"
  #when: ansible_host == ansible_all_ipv4_addresses[0]
  when: ansible_default_ipv4.address in ansible_host